kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ include "build-app.fullname" . }}
  labels:
    {{- include "build-app.labels" . | nindent 4 }}
spec:
  output:
    to:
      kind: DockerImage
      name: "{{ .Values.target.image.repository }}:{{ .Values.target.image.tag | default "latest" }}"
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: "{{ .Values.source.image.repository }}:{{ .Values.source.image.tag | default .Chart.AppVersion }}"
  source:
  source:
    binary: {}
  strategy:
    type: Binary
  runPolicy: Serial
